name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - run: dotnet tool restore
      - run: dotnet paket restore
      - run: dotnet pack src/FsJs/FsJs.fsproj --configuration Release  --include-symbols -p:SymbolPackageFormat=snupkg
      - run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.actor }}/index.json --name github
      - run: dotnet nuget push src/FsJs/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github --skip-duplicate
