name: build

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npx cypress info

      - run: dotnet tool restore && dotnet paket restore && dotnet build

      - uses: actions/checkout@v2
